

services:
  app:
    build: .
    image: laravel-livewire-app
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    networks:
      - laravel_network

  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: sistemaventas
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-}  # Permite contraseña vacía
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"      # Permite acceso sin contraseña
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
